version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: accident-postgis
    environment:
      POSTGRES_DB: accident_risk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: accident-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: accident-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: accident-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: accident-mlflow
    command: mlflow server --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"

volumes:
  postgres_data:
