app:
	name: road-accident-risk-platform
	env: development

fastapi:
	host: 0.0.0.0
	port: 8000

database:
	host: localhost
	port: 5432
	user: postgres
	password: changeme
	dbname: accident_risk

redis:
	host: localhost
	port: 6379

mlflow:
	tracking_uri: http://localhost:5000

