#!/usr/bin/env python3
"""
H2O AutoML Retraining - Online / Incremental

Purpose:
    Load merged retraining Parquet data from GCS, retrain the H2O AutoML
    model on the expanded dataset, log metrics to MLflow, and register
    a new version of the model in the MLflow Registry.

    This script is called by Airflow DAG `model_retrain_hourly` every hour.

Input:
    gs://big-data-group-4-gold/features/retrain/YYYYMMDD_HH/
    (generated by spark_merge_data task)

Output:
    MLflow experiment run with metrics, new model version in Registry.
    Flink automatically picks up the latest version.

Differences from train_before_2020.py:
    - Reads from dynamic GCS path (latest merged data).
    - Tags the run as "retrain_online".
    - Uses the same H2O AutoML + MLflow logging logic.
"""

import os
import logging
import h2o
from h2o.automl import H2OAutoML
import mlflow
import mlflow.h2o

# ============================================================
# Logging
# ============================================================

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("h2o-retrain-online")


# ============================================================
# Configuration
# ============================================================

# Dynamic path - use the latest merged retrain data on GCS
DEFAULT_DATA_PATH = os.getenv(
    "RETRAIN_DATA_PATH", "gs://big-data-group-4-gold/features/retrain/"
)

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "http://10.128.0.4:5000")
MLFLOW_EXPERIMENT_NAME = os.getenv("MLFLOW_EXPERIMENT_NAME", "traffic-risk-assessment")

MODEL_NAME = os.getenv("ML_MODEL_NAME", "traffic-risk-model")
MAX_RUNTIME_SECS = int(
    os.getenv("H2O_MAX_RUNTIME", "600")
)  # Shorter for hourly retrain
H2O_MAX_MEM = os.getenv("H2O_MAX_MEM", "2G")
H2O_NTHREADS = int(os.getenv("H2O_NTHREADS", "2"))

# Label column in the Parquet/CSV
LABEL_COLUMN = "true_severity"

# Columns to exclude from feature vector
EXCLUDED_COLUMNS = {
    "event_id",
    "event_year",
    "event_time",
    "true_severity",
}

SEED = int(os.getenv("H2O_SEED", "42"))


# ============================================================
# Helper: Safely log metrics that may not be available
# ============================================================
def log_metric_if_exists(perf, metric_name, mlflow_name=None, log_prefix="  "):
    """Safely extract a metric from H2O performance and log to MLflow + console."""
    if mlflow_name is None:
        mlflow_name = metric_name

    try:
        if metric_name in ("F1", "precision", "recall", "specificity", "sensitivity"):
            if hasattr(perf, metric_name):
                values = getattr(perf, metric_name)()
                for row in values:
                    class_label = row[0]
                    val = float(row[1])
                    mlflow.log_metric(f"{mlflow_name}_class_{class_label}", val)
                    logger.info(
                        "%s%s (class %s):          %.6f",
                        log_prefix,
                        metric_name.capitalize(),
                        class_label,
                        val,
                    )
                return True
        elif hasattr(perf, metric_name):
            val = float(getattr(perf, metric_name)())
            if not (val != val):  # NaN check
                mlflow.log_metric(mlflow_name, val)
                logger.info(
                    "%s%s:                   %.6f",
                    log_prefix,
                    metric_name.capitalize(),
                    val,
                )
                return True
    except (KeyError, AttributeError, TypeError, ValueError):
        pass

    logger.info("%s%s:                   N/A", log_prefix, metric_name.capitalize())
    return False


# ============================================================
# Find latest retrain data on GCS
# ============================================================
def find_latest_data(data_root: str) -> str:
    """
    Find the most recent retrain data directory on GCS.

    Expected GCS structure:
        gs://bucket/features/retrain/20260510_14/
        gs://bucket/features/retrain/20260510_15/
        ...
    """
    try:
        # Use gsutil to list directories
        import subprocess

        result = subprocess.run(
            ["gsutil", "ls", "-d", f"{data_root}*/"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        dirs = [line.strip() for line in result.stdout.splitlines() if line.strip()]
        if not dirs:
            logger.warning(
                "No retrain directories found. Falling back to offline data."
            )
            return os.getenv(
                "OFFLINE_TRAIN_INPUT",
                "gs://big-data-group-4-bronze/process/us_train_offline_before_2020.csv",
            )

        # Sort and return the latest
        latest = sorted(dirs)[-1]
        logger.info("Latest retrain data directory: %s", latest)
        return latest
    except Exception as e:
        logger.warning(
            "Could not list GCS directories: %s. Using default data path.", e
        )
        return os.getenv(
            "OFFLINE_TRAIN_INPUT",
            "gs://big-data-group-4-bronze/process/us_train_offline_before_2020.csv",
        )


# ============================================================
# Main training function
# ============================================================
def main():
    # Find the latest merged retrain data
    data_path = find_latest_data(DEFAULT_DATA_PATH)

    logger.info("=" * 80)
    logger.info("H2O AutoML Retraining - Online / Incremental")
    logger.info("=" * 80)
    logger.info("Data path:               %s", data_path)
    logger.info("MLflow tracking URI:     %s", MLFLOW_TRACKING_URI)
    logger.info("MLflow experiment:       %s", MLFLOW_EXPERIMENT_NAME)
    logger.info("Registered model name:   %s", MODEL_NAME)
    logger.info("Max runtime (seconds):   %s", MAX_RUNTIME_SECS)
    logger.info("H2O max memory:          %s", H2O_MAX_MEM)
    logger.info("H2O threads:             %s", H2O_NTHREADS)
    logger.info("Random seed:             %s", SEED)

    # ---- Step 1: Initialize H2O cluster ----
    logger.info("Step 1: Initializing H2O cluster...")
    h2o.init(
        max_mem_size=H2O_MAX_MEM,
        nthreads=H2O_NTHREADS,
    )
    logger.info("H2O cluster initialized.")

    # ---- Step 2: Configure MLflow ----
    logger.info("Step 2: Configuring MLflow tracking...")
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    mlflow.set_experiment(MLFLOW_EXPERIMENT_NAME)

    # ---- Step 3: Load data ----
    logger.info("Step 3: Loading retrain data from: %s", data_path)
    df_h2o = h2o.import_file(data_path)
    logger.info("Loaded %s rows, %s columns", f"{df_h2o.nrows:,}", df_h2o.ncols)

    df_h2o[LABEL_COLUMN] = df_h2o[LABEL_COLUMN].asfactor()

    label_dist = df_h2o[LABEL_COLUMN].table()
    logger.info("Label distribution:\n%s", label_dist)

    # ---- Step 4: Train/test split ----
    logger.info("Step 4: Splitting into train/test (80/20)...")
    train, test = df_h2o.split_frame(ratios=[0.8], seed=SEED)
    logger.info("Training rows:   %s", f"{train.nrows:,}")
    logger.info("Test rows:       %s", f"{test.nrows:,}")

    # ---- Step 5: Define features ----
    feature_columns = [c for c in df_h2o.columns if c not in EXCLUDED_COLUMNS]
    logger.info("Feature columns (%s): %s", len(feature_columns), feature_columns)
    logger.info("Label column:         %s", LABEL_COLUMN)

    # ---- Step 6: Train H2O AutoML ----
    logger.info("Step 6: Starting H2O AutoML retraining...")
    logger.info("Max runtime: %s seconds", MAX_RUNTIME_SECS)

    with mlflow.start_run(run_name="h2o_retrain_online") as run:
        run_id = run.info.run_id
        logger.info("MLflow run ID: %s", run_id)

        mlflow.log_param("run_type", "retrain_online")
        mlflow.log_param("max_runtime_secs", MAX_RUNTIME_SECS)
        mlflow.log_param("seed", SEED)
        mlflow.log_param("n_features", len(feature_columns))
        mlflow.log_param("n_train_rows", train.nrows)
        mlflow.log_param("n_test_rows", test.nrows)
        mlflow.log_param("data_path", data_path)

        aml = H2OAutoML(
            max_runtime_secs=MAX_RUNTIME_SECS,
            seed=SEED,
            project_name="traffic_risk_retrain",
            balance_classes=True,
            class_sampling_factors=[1.0, 1.5, 2.5, 4.0],
            max_after_balance_size=5.0,
        )

        aml.train(
            x=feature_columns,
            y=LABEL_COLUMN,
            training_frame=train,
        )

        logger.info("Training completed.")

        # ---- Step 7: Leaderboard ----
        lb = aml.leaderboard
        lb_df = lb.head(rows=5).as_data_frame()
        logger.info("H2O AutoML leaderboard (top 5):\n%s", lb_df)

        # ---- Step 8: Evaluate and log top 5 models ----
        top_model_ids = lb_df["model_id"].tolist()
        logger.info(
            "Step 8: Evaluating and logging top %s models...", len(top_model_ids)
        )

        best_model = None
        best_logloss = float("inf")

        for rank, model_id in enumerate(top_model_ids, start=1):
            model = h2o.get_model(model_id)
            model_perf = model.model_performance(test)

            current_logloss = float(model_perf.logloss())
            if current_logloss < best_logloss:
                best_logloss = current_logloss
                best_model = model

            logger.info("-" * 60)
            logger.info("Evaluating model rank %d: %s (%s)", rank, model_id, model.algo)

            with mlflow.start_run(
                run_name=f"retrain_top{rank}_{model.algo}", nested=True
            ):
                mlflow.log_param("rank", rank)
                mlflow.log_param("model_id", model_id)
                mlflow.log_param("algo", model.algo)

                log_metric_if_exists(model_perf, "logloss")
                log_metric_if_exists(model_perf, "mean_per_class_error")
                log_metric_if_exists(model_perf, "accuracy")
                log_metric_if_exists(model_perf, "rmse")
                log_metric_if_exists(model_perf, "mse")
                log_metric_if_exists(model_perf, "r2")
                log_metric_if_exists(model_perf, "auc")
                log_metric_if_exists(model_perf, "gini")
                log_metric_if_exists(model_perf, "F1")
                log_metric_if_exists(model_perf, "precision")
                log_metric_if_exists(model_perf, "recall")

                try:
                    if hasattr(model_perf, "confusion_matrix"):
                        cm = model_perf.confusion_matrix()
                        logger.info("  Confusion matrix:\n%s", cm)
                except (KeyError, AttributeError):
                    pass

                mlflow.h2o.log_model(model, artifact_path=f"retrain_model_rank{rank}")

        # ---- Step 9: Register best model ----
        logger.info("=" * 60)
        logger.info("Registering the best retrained model...")
        logger.info("Best model ID: %s", best_model.model_id)
        logger.info("Best model algorithm: %s", best_model.algo)
        logger.info("Best model logloss: %.6f", best_logloss)

        mlflow.h2o.log_model(best_model, artifact_path="best_model")

        model_uri = f"runs:/{run_id}/best_model"
        registered_model = mlflow.register_model(model_uri, MODEL_NAME)
        logger.info(
            "Model registered: name=%s, version=%s",
            registered_model.name,
            registered_model.version,
        )

        logger.info("Flink will automatically load models:/%s/latest", MODEL_NAME)

    # ---- Cleanup ----
    logger.info("Shutting down H2O cluster...")
    h2o.shutdown(prompt=False)

    logger.info("=" * 80)
    logger.info("Retraining complete. New model version in MLflow Registry.")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
